### ISSUE TITLE
Update to TypeScript 2.4.x

### ISSUE THREAD

**Issue by dylans** [dojo/typings#81]

**Comment by wspresto** [comment]
Evidently these typings do not work with tsc --version 2.2.3 or above,  you need to use 2.2.2

**Comment by dylans** [comment]
Hmmm, I thought we had actually recently done some updates to support 2.4.x... what's not working for you?

**Comment by wspresto** [comment]
When installing typescript from npm, I have to specify the version to be 2.2.2 . If I try anything higher, it complains about 
`Scripts/typings/dojo-typings/dijit/1.11/form.d.ts(283,13): error TS2430: Interface '_DateTimeTextBox<T>' incorrectly extends interface 'RangeBoundTextBox'.`

**Comment by dylans** [comment]
Hmmm, ok, it looks like that was missed in https://github.com/dojo/typings/commit/f59d6661956a3d3bb0d5fb5bbadd3c95dfe38921 ... we'll look into it asap.

**Comment by dylans** [comment]
@wspresto is it possible that you're not using the latest release of dojo/typings, as we're not having much luck reproducing your issue?
